public enum EventDefine
{
    ShowGamePanel,
    DecidePath,
    AddScore,
    UpdateScoreText,
    PlayerMove,
    AddDiamond,
    UpdateDiamondText,
    ShowGameOverPanel,
    ShowShopPanel,
    ShowMainPanel,
    ChangeSkin,
    Hint,
    ShowReSetPanel,
    ShowRankPanel,
    PlayClickAudio,
    IsMusicOn,
}
